### ISSUE TITLE
delete copy of my repo

### ISSUE THREAD

**Issue by robcalcroft** [JensPauwels/nvim#1]
Hey you've got a copy of my repo (https://www.npmjs.com/package/react-native-in-app-notification-fork) with no noticeable changes up on npm, I don't really mind that but its an old version that has my email address in it, would really appreciate if you could take it down from npm using https://stackoverflow.com/questions/36927974/how-to-delete-an-npm-package-from-the-npm-registry

**Comment by JensPauwels** [comment]
There was a reason to fork it, although i forgot the reason. Anyway, i don't use it anymore, so i removed it. Sorry for the inconvenience

**Comment by robcalcroft** [comment]
Thanks very much for doing that, really appreciated. All the best 😄
